//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_SERVIDOR
    {
        public string USUARIO_AUTH { get; set; }
        public string SENHA_AUTH { get; set; }
        public string ENDERECO_SERV_EMAIL { get; set; }
        public int PORTA_SERV_EMAIL { get; set; }
        public int SSL_SERV_EMAIL { get; set; }
        public string ENDERECO_APPLICACAO_REDIRECT { get; set; }
    }
}
