//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOACAO
    {
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public string DESCRICAO { get; set; }
        public string OBSERVACOES { get; set; }
        public int ID_ENTIDADE { get; set; }
        public int ID_DOADOR { get; set; }
        public System.DateTime DATA_HORA_CRIACAO_REGISTRO { get; set; }
    
        public virtual DOADOR DOADOR { get; set; }
        public virtual ENTIDADE ENTIDADE { get; set; }
    }
}
