//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADE()
        {
            this.ASSISTENCIA = new HashSet<ASSISTENCIA>();
            this.DOACAO = new HashSet<DOACAO>();
            this.ENTIDADE1 = new HashSet<ENTIDADE>();
            this.ESTOQUE = new HashSet<ESTOQUE>();
            this.EVENTO = new HashSet<EVENTO>();
            this.FORNECIMENTO = new HashSet<FORNECIMENTO>();
            this.RECURSO = new HashSet<RECURSO>();
            this.VOLUNTARIADO = new HashSet<VOLUNTARIADO>();
            this.VOLUNTARIO = new HashSet<VOLUNTARIO>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string LOGRADOURO { get; set; }
        public string NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string CEP { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string PRESIDENTE { get; set; }
        public bool ATIVA { get; set; }
        public string LOGIN_USUARIO_ADMINISTRADOR { get; set; }
        public Nullable<int> ID_ENTIDADE_CONTROLADORA { get; set; }
        public System.DateTime DATA_HORA_CRIACAO_REGISTRO { get; set; }
        public string CNPJ { get; set; }
        public string TELEFONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSISTENCIA> ASSISTENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOACAO> DOACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTIDADE> ENTIDADE1 { get; set; }
        public virtual ENTIDADE ENTIDADE2 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTOQUE> ESTOQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORNECIMENTO> FORNECIMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSO> RECURSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOLUNTARIADO> VOLUNTARIADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOLUNTARIO> VOLUNTARIO { get; set; }
    }
}
