//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORNECIMENTO()
        {
            this.FORNECIMENTO_ITENS = new HashSet<FORNECIMENTO_ITENS>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public string OBSERVACOES { get; set; }
        public int ID_FORNECEDOR { get; set; }
        public int ID_ENTIDADE { get; set; }
        public System.DateTime DATA_HORA_CRIACAO_REGISTRO { get; set; }
    
        public virtual ENTIDADE ENTIDADE { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORNECIMENTO_ITENS> FORNECIMENTO_ITENS { get; set; }
    }
}
