//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO_PERMISSAO1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO_PERMISSAO1()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public bool PERM_ENTIDADE { get; set; }
        public bool PERM_VOLUNTARIOS { get; set; }
        public bool PERM_VOLUNTARIAR { get; set; }
        public bool PERM_VOLUNTARIADO { get; set; }
        public bool PERM_USUARIOS { get; set; }
        public bool PERM_GRUPOPERMISSAO { get; set; }
        public bool PERM_EVENTO { get; set; }
        public bool PERM_TIPOEVENTO { get; set; }
        public bool PERM_RECURSO { get; set; }
        public bool PERM_TIPORECURSO { get; set; }
        public bool PERM_FORNECEDOR { get; set; }
        public bool PERM_FORNECIMENTO { get; set; }
        public bool PERM_PRODUTO { get; set; }
        public bool PERM_TIPOPRODUTO { get; set; }
        public bool PERM_DOACAO { get; set; }
        public bool PERM_DOADOR { get; set; }
        public bool PERM_ASSISTENCIA { get; set; }
        public bool PERM_ASSISTIDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
