//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECUPERACAO_SENHA
    {
        public string LOGIN_USUARIO { get; set; }
        public string CHAVE { get; set; }
        public System.DateTime DATA_CRIACAO { get; set; }
        public System.DateTime DATA_EXPIRACAO { get; set; }
        public int VALIDADO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
