//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA_ITEM_ENTIDADE
    {
        public int ID_SISTEMA_ENTIDADE { get; set; }
        public int ID_GRUPO_PERMISSAO { get; set; }
    
        public virtual GRUPO_PERMISSAO GRUPO_PERMISSAO { get; set; }
        public virtual SISTEMA_ENTIDADE SISTEMA_ENTIDADE { get; set; }
    }
}
