//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA_ITEM_ENTIDADE_CONSULTA : SISTEMA_ITEM_ENTIDADE
    {
        public bool consultar { get; set; }
    }
}
