//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLUNTARIADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOLUNTARIADO()
        {
            this.VOLUNTARIAR = new HashSet<VOLUNTARIAR>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATA_INICIAL { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string DESCRICAO { get; set; }
        public string OBSERVACAO { get; set; }
        public int ID_ENTIDADE { get; set; }
        public System.DateTime DATA_HORA_CRIACAO_REGISTRO { get; set; }
    
        public virtual ENTIDADE ENTIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOLUNTARIAR> VOLUNTARIAR { get; set; }
    }
}
